---
apiVersion: v1
kind: ReplicationController
metadata:
  name: petclinic
  labels:
    app: petclinic
    version: "1.0"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic-container
          image: registry.default.svc.appfactory.local:5000/petclinic
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: "http-server"

---
kind: Service
apiVersion: v1
metadata:
  name: petclinic-pub
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080
  selector:
    app: petclinic
